# Generated by Django 6.0.5 on 2026-05-09 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('sales_b2b', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingtransaction',
            name='b2b_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_b2b.b2bsale'),
        ),
    ]
