# Generated by Django 6.0.5 on 2026-05-09 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sales_b2c', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='b2creturn',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2creturnitem',
            name='return_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_b2c.b2creturn'),
        ),
        migrations.AddField(
            model_name='b2csale',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2csale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_b2c.b2ccustomer'),
        ),
        migrations.AddField(
            model_name='b2creturn',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_b2c.b2csale'),
        ),
        migrations.AddField(
            model_name='b2csaleitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='b2csaleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_b2c.b2csale'),
        ),
        migrations.AddField(
            model_name='b2creturnitem',
            name='sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_b2c.b2csaleitem'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales_b2c.b2csale'),
        ),
    ]
