# Generated by Django 6.0.5 on 2026-05-09 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_b2c', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2creturnitem',
            name='return_obj',
        ),
        migrations.AddField(
            model_name='b2creturnitem',
            name='b2c_return',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_b2c.b2creturn'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='b2ccustomer',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='b2ccustomer',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='b2csale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='b2csaleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_b2c.b2csale'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='b2ccustomer',
            table='b2c_customers',
        ),
        migrations.AlterModelTable(
            name='b2creturn',
            table='b2c_returns',
        ),
        migrations.AlterModelTable(
            name='b2creturnitem',
            table='b2c_return_items',
        ),
        migrations.AlterModelTable(
            name='b2csale',
            table='b2c_sales',
        ),
        migrations.AlterModelTable(
            name='b2csaleitem',
            table='b2c_sale_items',
        ),
        migrations.AlterModelTable(
            name='bill',
            table='bills',
        ),
    ]
