# Generated by Django 6.0.5 on 2026-05-09 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('sales_b2c', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='b2c_return_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_b2c.b2creturnitem'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='b2c_sale_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_b2c.b2csaleitem'),
        ),
    ]
