# Generated by Django 6.0.5 on 2026-05-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='reorder_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='inventory',
        ),
        migrations.AlterModelTable(
            name='inventorylog',
            table='inventory_logs',
        ),
    ]
