# Generated by Django 6.0.5 on 2026-05-09 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_reorder_level_and_more'),
        ('products', '0002_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylog',
            name='b2b_return_item',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='b2b_sale_item',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='b2c_return_item',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='b2c_sale_item',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='purchase_item',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='purchase_return_item',
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='reference_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.productvariant'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('purchase_return', 'Purchase Return'), ('b2c_sale', 'B2C Sale'), ('b2c_return', 'B2C Return'), ('b2b_sale', 'B2B Sale'), ('b2b_return', 'B2B Return'), ('adjustment', 'Adjustment')], max_length=50),
        ),
    ]
