# Generated by Django 6.0.4 on 2026-05-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_stock_product_regular_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
