# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("warehouse_staff", "Warehouse Staff"),
                    ("warehouse", "Warehouse"),
                ],
                default="warehouse_staff",
                max_length=20,
            ),
        ),
    ]
