# Generated by Django 6.0.5 on 2026-05-09 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sales_b2b', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='b2breturn',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2breturnitem',
            name='return_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_b2b.b2breturn'),
        ),
        migrations.AddField(
            model_name='b2bsale',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2bsale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_b2b.b2bcustomer'),
        ),
        migrations.AddField(
            model_name='b2breturn',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_b2b.b2bsale'),
        ),
        migrations.AddField(
            model_name='b2bsaleitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='b2bsaleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_b2b.b2bsale'),
        ),
        migrations.AddField(
            model_name='b2breturnitem',
            name='sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_b2b.b2bsaleitem'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales_b2b.b2bsale'),
        ),
    ]
