# Generated by Django 6.0.5 on 2026-05-09 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_b2b', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b2breturn',
            old_name='sale',
            new_name='b2b_sale',
        ),
        migrations.RenameField(
            model_name='b2breturnitem',
            old_name='sale_item',
            new_name='b2b_sale_item',
        ),
        migrations.RenameField(
            model_name='b2bsale',
            old_name='customer',
            new_name='b2b_customer',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='sale',
            new_name='b2b_sale',
        ),
        migrations.RemoveField(
            model_name='b2breturnitem',
            name='return_obj',
        ),
        migrations.RemoveField(
            model_name='b2bsaleitem',
            name='sale',
        ),
        migrations.AddField(
            model_name='b2breturnitem',
            name='b2b_return',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_b2b.b2breturn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2bsaleitem',
            name='b2b_sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_b2b.b2bsale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='b2bsale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='b2bcustomer',
            table='b2b_customers',
        ),
        migrations.AlterModelTable(
            name='b2breturn',
            table='b2b_returns',
        ),
        migrations.AlterModelTable(
            name='b2breturnitem',
            table='b2b_return_items',
        ),
        migrations.AlterModelTable(
            name='b2bsale',
            table='b2b_sales',
        ),
        migrations.AlterModelTable(
            name='b2bsaleitem',
            table='b2b_sale_items',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='invoices',
        ),
    ]
