# Generated by Django 6.0.4 on 2026-05-04 10:55

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('hex_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, e.g. #FF5733 or #FFF.', regex=re.compile('^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$'))])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
